authentic/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.home, name=""),
    
    path('register', views.register, name="register"),
    
    path('login', views.login, name="login"),
    
    path('dashboard', views.dashboard, name="dashboard"),
    
    path('contact', views.contact, name="contact"),
    
    path('about', views.about, name="about"),
    
    path('services', views.xray, name="X-ray"),
        
    path('symptom', views.diagnosis, name="symptomes"),
    
    path('diagnosis', views.diagnosis, name='diagnosis-result'), 
    
    path('logout', views.logout, name="logout"),
    
    
    

    
]

smartmed/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentic.urls')),
]

authentic/models.py
from django.db import models


class Symptomis(models.Model):
    name =  models.CharField(max_length=100)
    def __str__(self):
        return self.name
        


class Diagnosis(models.Model):
    name = models.CharField('name',max_length=120) 
    cin = models.CharField('cin',max_length=15)
    symptom1 = models.ForeignKey(Symptomis, on_delete=models.SET_NULL,null=True, related_name='symtpom1')
    symptom2 = models.ForeignKey(Symptomis, on_delete=models.SET_NULL,null=True, related_name='symtpom2')
    symptom3 = models.ForeignKey(Symptomis, on_delete=models.SET_NULL,null=True, related_name='symtpom3')
    symptom4 = models.ForeignKey(Symptomis, on_delete=models.SET_NULL,null=True, related_name='symtpom4')
    symptom5 = models.ForeignKey(Symptomis, on_delete=models.SET_NULL,null=True, related_name='symtpom5')
    def __str__(self):
        return self.name
    
    
class Finalis(models.Model):
    info = models.ForeignKey(Diagnosis, on_delete=models.SET_NULL,null=True, related_name='info')
    diag = models.CharField('diag',max_length=120)

class UploadedImage(models.Model):
    image = models.ImageField(upload_to='uploaded_images/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

authentic/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from django.forms.widgets import PasswordInput, TextInput
from .models import Diagnosis
from .models import UploadedImage
#This form is for registrating/creating a user(Model Form)

class CreateUserForm(UserCreationForm): 
    
    class Meta:
        
        model = User
        fields = ['username', 'email', 'password1', 'password2'] #two passwords because the user will have to re-enter the pass for verification
        
        
#This form is for authentication a user(Model Form)

class LoginForm(AuthenticationForm):
    
    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())
    


#Symptoms form:
class Know_Disease(forms.ModelForm):
    class Meta:
        model = Diagnosis
        fields = ('name','cin','symptom1','symptom2','symptom3','symptom4','symptom5')

class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UploadedImage
        fields = ['image'] 

authentic/views.py
from django.shortcuts import render, redirect
from .forms import CreateUserForm, LoginForm, UploadImageForm
import numpy as np
import pandas as pd
import os
from .predict import predict_image 
from .predict import predict_image_tuberculosis



#to stop a user from accessing to the dashboard if he's loged out

from django.contrib.auth.decorators import login_required

#These are auth models & functions

from django.contrib.auth.models import auth 
from django.contrib.auth import authenticate, login, logout
from .forms import Know_Disease
from .disease2 import NaiveBayes 
from .models import Finalis
from tensorflow import keras

def home(request):
    
    return render(request, 'index.html')


def register(request):
    
    form = CreateUserForm()
    
    if request.method == "POST": #if we got a post from the register.html page
        
        form = CreateUserForm(request.POST)  #then the user infos will be sent to the DB

        if form.is_valid():  #checks if the infos are valid/no error
            
            form.save()  #pushes all the data  to the DB if it's valid

            return redirect("login") #after registration, the user will be redirected to the login page
        
    context = {'registerform': form}     #this is to render the form to the register.html
    
    return render(request, 'register.html', context=context)



def login(request):
    
    form = LoginForm()
    
    if request.method == 'POST':
        
        form = LoginForm(request, data=request.POST)
        
        if form.is_valid():
            
            username = request.POST.get('username')
            password = request.POST.get('password')
            
            user = authenticate(request, username=username, password=password)

            if user is not None:
                
                auth.login(request, user)
                
                return redirect("dashboard")
            
    context = {'loginform':form}
    
    
    return render(request, 'login.html', context=context)



def logout(request):
    
    auth.logout(request)
    
    return redirect("")




@login_required(login_url="login")
def dashboard(request):
    
    return render(request, 'index.html')


def about(request):
    
    return render(request, 'about.html')

def contact(request):
    
    return render(request, 'contact.html')

#############################################################
def xray(request):
    if request.method == 'POST':
        form = UploadImageForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_image = form.save()  # Save the uploaded image
            image_path = uploaded_image.image.path  # Path of the image on the filesystem
            
            # Check which button was clicked
            disease = request.POST.get('disease')
            
            if disease == 'pneumonie':
                prediction_label = predict_image(image_path, 'cnn_model.h5')  # Predict Pneumonia
            elif disease == 'tuberculosis':
                prediction_label = predict_image_tuberculosis(image_path, 'cnn_model1.h5')  # Predict Tuberculosis
            else:
                prediction_label = 'Unknown disease'
            
            return render(request, 'services/X-ray.html', {'form': form, 'prediction_label': prediction_label})
    else:
        form = UploadImageForm()
    return render(request, 'services/X-ray.html', {'form': form})


##############################################################
# def xray_pneu(request):
#     if request.method == 'POST':
#         form = UploadImageForm(request.POST, request.FILES)
#         if form.is_valid():
#             uploaded_image = form.save()  # Sauvegarde de l'image téléchargée
#             image_path = uploaded_image.image.path  # Chemin de l'image sur le système de fichiers
#             prediction_label = predict_image(image_path, 'cnn_model.h5')  # Prédiction de la maladie
#             return render(request, 'services/X-ray.html', {'form': form, 'prediction_label': prediction_label})
#     else:
#         form = UploadImageForm()
#     return render(request, 'services/X-ray.html', {'form': form})

################################Covid Prediction############
# def xray_tub(request):
#     if request.method == 'POST':
#         form = UploadImageForm(request.POST, request.FILES)
#         if form.is_valid():
#             uploaded_image = form.save()  # Sauvegarde de l'image téléchargée
#             image_path = uploaded_image.image.path  # Chemin de l'image sur le système de fichiers
#             prediction_label = predict_image_tuberculosis(image_path, 'cnn_model1.h5')  # Prédiction de la maladie
#             return render(request, 'services/X-ray.html', {'form': form, 'prediction_label': prediction_label})
#     else:
#         form = UploadImageForm()
#     return render(request, 'services/X-ray.html', {'form': form})

#############################################################
def diagnosis(request):
    if request.method == 'POST':
        form = Know_Disease(request.POST)
        if form.is_valid():
            form.save()
            symptoms = [
                form.cleaned_data['symptom1'],
                form.cleaned_data['symptom2'],
                form.cleaned_data['symptom3'],
                form.cleaned_data['symptom4'],
                form.cleaned_data['symptom5']
            ]
            symptoms = [symptom_instance.name for symptom_instance in symptoms]
            prediction = NaiveBayes(symptoms)
            instance = form.save()

            final = Finalis.objects.create(
                info=instance,
                diag=prediction
            )
            
            context = {'form': form, 'predicted_disease1': prediction, 'symptoms': symptoms}
            return render(request, "Services/result.html", context)
    else:
        form = Know_Disease()
        context = {'form': form}
        return render(request, "Services/symp.html", context)
   

authentic/templates/Services/X-ray.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://kit.fontawesome.com/168ebc7feb.js" crossorigin="anonymous"></script>
    <link
      rel="stylesheet"
      href="https://unpkg.com/flowbite@1.5.4/dist/flowbite.min.css"
    />
    <link
      rel="stylesheet"
      href="https://unpkg.com/flowbite@1.5.4/dist/flowbite.min.css"
    />
    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.25.0/axios.min.js"
      integrity="sha512-/Q6t3CASm04EliI1QyIDAA/nDo9R8FQ/BULoUFyN4n/BDdyIxeH7u++Z+eobdmr11gG5D/6nPFyDlnisDwhpYA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>

    <title>X-ray Page</title>
    <!-- <link rel="stylesheet" type="text/css" href="x-ray.css"> -->
    <style>
        body {
            background: linear-gradient(115deg, #3369ef, #3b83ff, #53baff);     background-size: cover;
             background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-position: center; 
        }

        h1 {
            color: #fffbfb;
        }
        
          .containe{
            margin:50px;
          }
          .containe h1{
            font-weight: bold; /* Make the title bold */
 color: white;    text-align: center; /* Center align content */

          }
        .btn-danger {
    background-color: #dd4bc5;
    border-color: #ff98ee;
}

.btn-danger:hover {
    background-color: #e74ece;
    border-color: #e74ece;
}
.global{
    display: flex;
    flex-direction: column;
    margin-left: 30px;
    margin-right: 30px;
}
      </style>
  </head>
  <body>
    <nav class="bg-gradient-to-r from-blue-700 to-[#ffffff00] py-2 w-full px-24 flex justify-between shadow-lg backdrop-blur-md z-50">
        <a href="" class="flex items-center">
          <!-- Image placed beside the title -->
          <img src="{% static "logo.png" %}" alt="MedSmart Logo" class="h-8 mr-2">
          <!-- Title -->
          <p class="font-Inter font-bold text-lg text-white">MedSmart</p>
        </a>
        <div class="flex">
          <ul class="flex text-white font-mono mr-8">
            <li class="mx-4 py-2 hover:underline transition-all ease-in hover:text-slate-200">
              <a class="rounded bg-blue-500 px-4 py-2" href="#about">About Us</a>
            </li>
            <li class="mx-4 py-2 hover:underline transition-all ease-in hover:text-slate-200">
              <a class="rounded bg-blue-500 px-4 py-2" href="#services">Services</a>
            </li>
            <li class="mx-4 py-2 hover:underline transition-all ease-in hover:text-slate-200">
              <a class="rounded bg-blue-500 px-4 py-2" href="#call">Contact</a>
            </li>
          </ul>
          <button
            type="button"
            class="text-white  bg-blue-500 hover:bg-blue-600 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"
          >
            Login
          </button>
        </div>
      </nav>
<div>    
 <div  class="global"> 
    <div class="containe">
        <h1>X-ray Analyzer</h1>
      </div>
      <div class="row">
        <div class="card col-md-3 mx-auto">
          <div class="card-header text-center">Menu</div>
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="my-3 text-center">
                {{ form.as_p }}
                <input
                type="file"
                id="xrayimg"
                accept="image/*"
                style="display: none"
                onchange="showPreview(event)"
                />
              </div>
          
              <div class="my-3 text-center d-flex justify-content-center">
                {% comment %} <button type="submit" id="tclassi" class="w-75 btn btn-primary enabled">
                  Pneumonie
                </button>
                <button type="submit" id="tclassi" class="w-75 btn btn-primary enabled ms-2">
                  Tuberculosis
                </button>  {% endcomment %}
                   <button type="submit" name="disease" value="pneumonie" class="w-75 btn btn-primary enabled">
                      Pneumonie
                  </button>
                  <button type="submit" name="disease" value="tuberculosis" class="w-75 btn btn-primary enabled ms-2">
                      Tuberculosis
                  </button> 
              </form>
              
              </div>
            </form>
<!-- ****************si on fait un seul algorithme pour toutes les maladies 
=> on va utiliser un seul boutton pour  l'Analyse de l'image************ -->
            <!-- <div class="my-3 text-center">
              <button
                onclick="postImage()"
                id="tclassi"
                class="w-75 btn btn-primary disabled"
              >
                Analyze an X-Ray Image
              </button>
            </div> -->
              
            <div class="my-3 row text-center">
              <div class="col-lg-5 pt-1">
                <p class="Classification"></p>
              </div>
            </div>
            <div class="my-3 text-center">
              <button
                class="btn btn-danger w-75"
                onclick="window.location.reload()"
                type="reset"
              >
                Reset
              </button>
            </div>
          </div>
        </div>
        <div class="card col-md-4 mx-auto ">
          <div class="card-header text-center">Input X-Ray Image</div>
          <div class="row h-100 justify-content-center align-items-center">
            <img
              id="imageshow"
              src=""
              class="align-self-center"
              height="100px"
              width="100px"
              style="aspect-ratio: unset; box-sizing: content-box"
            />
          </div>
        </div>
        <div class="card col-md-4 mx-auto">
          <div class="card-header text-center">Result</div>
          
          <div class="row h-100 justify-content-center align-items-center">
            <p
              id="photo"
              src=""
              class="align-self-center"
              height="0px"
              width="0px"
              style="aspect-ratio: unset; box-sizing: content-box"
            > Resultat de la prédiction : {{ prediction_label }}</p>
          </div>
        </div>
      </div>
    </div>
</div>
</div>    
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <script type="text/javascript">
      const imageget = document.getElementById("imageshow");
      const showimg = document.getElementById("photo");
      imageget.addEventListener("load", () => {
        console.log("image");
        if (imageget.src === "") {
          imageget.style.width = "0px";
          imageget.style.height = "0px";
        } else {
          imageget.style.width = "300px";
          imageget.style.height = "300px";
        }
      });
      showimg.addEventListener("load", () => {
        console.log("image");
        if (imageget.src === "") {
          showimg.style.width = "0px";
          showimg.style.height = "0px";
        } else {
          showimg.style.width = "300px";
          showimg.style.height = "300px";
        }
      });
      let fileData = new FormData();
      function showPreview(event) {
        if (event.target.files.length > 0) {
          console.log(event);
          var Classification = document.getElementById("tclassi");
          fileData.append("image", event.target.files[0]);
          var src = URL.createObjectURL(event.target.files[0]);
          var preview = document.getElementById("imageshow");
          Classification.classList.remove("disabled");
          preview.src = src;
          preview.style.display = "block";
        }
      }
      function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== "") {
          const cookies = document.cookie.split(";");
          for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === name + "=") {
              cookieValue = decodeURIComponent(
                cookie.substring(name.length + 1)
              );
              break;
            }
          }
        }
        return cookieValue;
      }
      var Base64 = {
        _keyStr:
          "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",
        encode: function (e) {
          var t = "";
          var n, r, i, s, o, u, a;
          var f = 0;
          e = Base64._utf8_encode(e);
          while (f < e.length) {
            n = e.charCodeAt(f++);
            r = e.charCodeAt(f++);
            i = e.charCodeAt(f++);
            s = n >> 2;
            o = ((n & 3) << 4) | (r >> 4);
            u = ((r & 15) << 2) | (i >> 6);
            a = i & 63;
            if (isNaN(r)) {
              u = a = 64;
            } else if (isNaN(i)) {
              a = 64;
            }
            t =
              t +
              this._keyStr.charAt(s) +
              this._keyStr.charAt(o) +
              this._keyStr.charAt(u) +
              this._keyStr.charAt(a);
          }
          return t;
        },
        decode: function (e) {
          var t = "";
          var n, r, i;
          var s, o, u, a;
          var f = 0;
          e = e.replace(/[^A-Za-z0-9\+\/\=]/g, "");
          while (f < e.length) {
            s = this._keyStr.indexOf(e.charAt(f++));
            o = this._keyStr.indexOf(e.charAt(f++));
            u = this._keyStr.indexOf(e.charAt(f++));
            a = this._keyStr.indexOf(e.charAt(f++));
            n = (s << 2) | (o >> 4);
            r = ((o & 15) << 4) | (u >> 2);
            i = ((u & 3) << 6) | a;
            t = t + String.fromCharCode(n);
            if (u != 64) {
              t = t + String.fromCharCode(r);
            }
            if (a != 64) {
              t = t + String.fromCharCode(i);
            }
          }
          t = Base64._utf8_decode(t);
          return t;
        },
        _utf8_encode: function (e) {
          e = e.replace(/\r\n/g, "\n");
          var t = "";
          for (var n = 0; n < e.length; n++) {
            var r = e.charCodeAt(n);
            if (r < 128) {
              t += String.fromCharCode(r);
            } else if (r > 127 && r < 2048) {
              t += String.fromCharCode((r >> 6) | 192);
              t += String.fromCharCode((r & 63) | 128);
            } else {
              t += String.fromCharCode((r >> 12) | 224);
              t += String.fromCharCode(((r >> 6) & 63) | 128);
              t += String.fromCharCode((r & 63) | 128);
            }
          }
          return t;
        },
        _utf8_decode: function (e) {
          var t = "";
          var n = 0;
          var r = (c1 = c2 = 0);
          while (n < e.length) {
            r = e.charCodeAt(n);
            if (r < 128) {
              t += String.fromCharCode(r);
              n++;
            } else if (r > 191 && r < 224) {
              c2 = e.charCodeAt(n + 1);
              t += String.fromCharCode(((r & 31) << 6) | (c2 & 63));
              n += 2;
            } else {
              c2 = e.charCodeAt(n + 1);
              c3 = e.charCodeAt(n + 2);
              t += String.fromCharCode(
                ((r & 15) << 12) | ((c2 & 63) << 6) | (c3 & 63)
              );
              n += 3;
            }
          }
          return t;
        },
      };
      {% comment %} function postImage() {
        axios
          .post("", fileData, {
            headers: {
              "Content-Type": "multipart/form-data",
              "X-CSRFToken": getCookie("csrftoken"),
            },
          })
          .then((response) => {
            console.log(response);
            document.getElementsByClassName("Classification")[0].textContent =
              response.data.label;
            document.getElementById(
              "photo"
            ).src = data;image/png;base64,$;{response.data.photo.slice(2, -1)};
          })
          .then((error) => {
            console.log(error);
          });
      } {% endcomment %}
      {% comment %} function postImage() {
        var formData = new FormData();
        formData.append('image', document.getElementById('xrayimg').files[0]);
        
        $.ajax({
            type: 'POST',
            url: '/predict_xray/',  // Assurez-vous de remplacer '/predict_xray/' par l'URL de votre vue Django
            data: formData,
            processData: false,
            contentType: false,
            success: function(response) {
                document.getElementById('photo').textContent = "Résultat de la prédiction : " + response.prediction_label;
            },
            error: function(xhr, status, error) {
                console.error(xhr.responseText);
            }
        });
    } {% endcomment %}
    
    </script>
  </body>
</html>

authentic/templates/Services/symp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://kit.fontawesome.com/168ebc7feb.js" crossorigin="anonymous"></script>
    <link
      rel="stylesheet"
      href="https://unpkg.com/flowbite@1.5.4/dist/flowbite.min.css"
    />
    <title>Symptom Checker Form</title>
    {% load static %}
    <style>
        body {
            margin: 0;
            padding: 0;
            background-image: url({% static "3522195.jpg" %});
            background-size: cover;
        }
    
        .container {
            width: 80%%;
            max-width: 500px;
            margin: 50px auto;
            padding: 30px;
            border: 1px solid #000000;
            border-radius: 5px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.8);
        }
    
        .container h2 {
            font-weight: bold;
            color: white;
            text-align: center;
        }
    
        .form-group {
            margin-bottom: 20px;
        }
    
        label {
            display: block;
            margin-bottom: 5px;
        }
    
        input[type="text"],
        select {
            width: calc(100% - 10px);
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
    
        button {
            margin: 30px;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            {% comment %} width: 400px; {% endcomment %}
        }
    
        button:hover {
            background-color: #0056b3;
        }
        #submit-button {
            display: block;
            margin: 20px auto 0; /* Added 20px top margin */; /* Center the button horizontally */
            width: 200px; /* Set desired width */
            padding: 15px 30px; /* Set desired padding */
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 1rem;
        }
    
        .symptom-inputs {
            display: flex;
            flex-wrap: wrap;
        }
    
        .symptom-input {
            flex: 0 0 50%;
        }
    
        @media (max-width: 600px) {
            .symptom-input {
                flex: 0 0 100%;
                padding-right: 0;
            }
        }
    
        label {
            display: block;
            margin-bottom: 5px;
            color: white;
        }
    </style>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
</head>

<body>
    <!-- Added navbar from index.html -->
    <nav class="bg-gradient-to-r from-blue-700 to-[#ffffff00] py-2 w-full px-24 flex justify-between shadow-lg backdrop-blur-md z-50">
        <a href="" class="flex items-center">
          <!-- Image placed beside the title -->
          <img src="{% static "logo.png" %}" alt="MedSmart Logo" class="h-8 mr-2">
          <!-- Title -->
          <p class="font-Inter font-bold text-lg text-white">MedSmart</p>
        </a>
        <div class="flex">
          <ul class="flex text-white font-mono mr-8">
            <li class="mx-4 py-2 hover:underline transition-all ease-in hover:text-slate-200">
              <a class="rounded bg-blue-500 px-4 py-2" href="#about">About Us</a>
            </li>
            <li class="mx-4 py-2 hover:underline transition-all ease-in hover:text-slate-200">
              <a class="rounded bg-blue-500 px-4 py-2" href="#services">Services</a>
            </li>
            <li class="mx-4 py-2 hover:underline transition-all ease-in hover:text-slate-200">
              <a class="rounded bg-blue-500 px-4 py-2" href="#call">Contact</a>
            </li>
          </ul>
          <button
            type="button"
            class="text-white  bg-blue-500 hover:bg-blue-600 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"
          >
            Login
          </button>
        </div>
      </nav>
    <!-- Rest of the code remains the same -->
    <div class="container">
        <h2>Find Your Disease</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_div }}
            <button type="submit" id="submit-button" class="btn btn-primary">Submit</button>
        </form>
    </div>

    <!-- Additional scripts if needed -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $("#id_symptom1").select2();
        $("#id_symptom2").select2();
        $("#id_symptom3").select2();
        $("#id_symptom4").select2();
        $("#id_symptom5").select2();
    </script>
</body>
</html>